version: 2.1
setup: true

orbs:
  continuation: circleci/continuation@1.0.0

jobs:
  setup: 
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: setup
          command: echo "In setup phase"

  say-hello-master:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Say hello
          command: echo "Hello - on master branch"

  say-hello-pr:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Say hello
          command: "echo Hello - from PR"

workflows:
  setup:
    when:
      equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - setup

  say-hello-master:
    jobs:
      - say-hello-master:
          filters:
            branches:
              only: master

  say-hello-pr:
    when:
      not:
        equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - say-hello-pr:
          filters:
            branches:
              ignore: master

