version: 2.1
setup: true

orbs:
  continuation: circleci/continuation@1.0.0

jobs:

  # ********** SETUP ********** 

  setup-pr: 
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: setup - pr
          command: echo "In setup phase - for PR"
      - continuation/continue:
          configuration_path: .circleci/pr-config.yml

  # ********** MERGE TO MASTER JOBS **********

  say-hello-master-1:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Say hello - master 1
          command: "echo Hello - merge from master 1"

  say-hello-master-2-1:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Say hello - master - workflow 2 - job 1
          command: "echo Hello - merge from master - workflow 2, job 1"

  say-hello-master-2-2:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Say hello - master - workflow 2 - job 2
          command: "echo Hello - merge from master - workflow 2, job 2"

  # ********** SCHEDULED JOBS **********

  say-hello-schedule-1:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Say hello - schedule 1
          command: "echo Hello - from schedule-1"

  say-hello-schedule-2:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Say hello - schedule 2
          command: "echo Hello - from schedule-2"

  say-hello-schedule-3:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Say hello - schedule 3
          command: "echo Hello - from schedule-3"

  say-hello-schedule-4:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Say hello - schedule 4
          command: "echo Hello - from schedule-4"

workflows:

  # ********** SETUP WORKFLOW **********

  setup-pr:
    when:
      and:
        - not:
            equal: [ master, << pipeline.git.branch >> ]
        - not:
            equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - setup-pr:
          filters:
              branches:
                ignore: master

  setup-master:
    when:
      not:
        equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - setup-master:
          filters:
              branches:
                only: master

  # ********** MERGE TO MASTER WORKFLOW **********

  merge-to-master-wf-1:
    when:
      and:
        - equal: [ master, << pipeline.git.branch >> ]
        - not:
            equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - say-hello-master-1

  merge-to-master-wf-2:
    when:
      and:
        - equal: [ master, << pipeline.git.branch >> ]
        - not:
            equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - say-hello-master-2-1
      - say-hello-master-2-2

  # ********** SCHEDULED WORKFLOW **********

  schedule-1:
    when:
      and:
        - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
        - equal: [ schedule-1, << pipeline.schedule.name >> ]
    jobs:
      - say-hello-schedule-1

  schedule-2:
    when:
      and:
        - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
        - equal: [ schedule-2, << pipeline.schedule.name >> ]
    jobs:
      - say-hello-schedule-2

  schedule-3:
    when:
      and:
        - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
        - equal: [ schedule-3, << pipeline.schedule.name >> ]
    jobs:
      - say-hello-schedule-3

  schedule-4:
    when:
      and:
        - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
        - equal: [ schedule-4, << pipeline.schedule.name >> ]
    jobs:
      - say-hello-schedule-4

