version: 2.1
setup: true

orbs:
  continuation: circleci/continuation@1.0.0

jobs:
  setup-pr: 
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: setup
          command: echo "In setup phase - for PR"
      - continuation/continue:
          configuration_path: .circleci/pr-config.yml

  setup-master: 
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: setup
          command: echo "In setup phase - for master"
      - continuation/continue:
          configuration_path: .circleci/master-config.yml

workflows:
  setup-pr:
    when:
      not:
        equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - setup-pr:
          filters:
              branches:
                ignore: master

  setup-master:
    when:
      not:
        equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - setup-master:
          filters:
              branches:
                only: master

  # schedule-1:
  #   when:
  #     equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
  #   jobs:
  #     - schedule-1

  # schedule-2:
  #   when:
  #     equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
  #   jobs:
  #     - schedule-2

  # schedule-3:
  #   when:
  #     equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
  #   jobs:
  #     - schedule-3

  # schedule-4:
  #   when:
  #     equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
  #   jobs:
  #     - schedule-4

