version: 2.1
setup: true

orbs:
  continuation: circleci/continuation@1.0.0

jobs:

  # ********** SETUP JOBS ********** 

  setup-pr: 
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: setup - pr
          command: echo "In setup phase - for PR"
      - continuation/continue:
          configuration_path: .circleci/pr-config.yml

  setup-master: 
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: setup - master
          command: echo "In setup phase - for master"
      - continuation/continue:
          configuration_path: .circleci/master-config.yml

  # ********** SCHEDULED JOBS **********

  say-hello-schedule-1:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Say hello - schedule 1
          command: "echo Hello - from schedule-1"

  say-hello-schedule-2:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Say hello - schedule 2
          command: "echo Hello - from schedule-2"

  say-hello-schedule-3:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Say hello - schedule 3
          command: "echo Hello - from schedule-3"

  say-hello-schedule-4:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Say hello - schedule 4
          command: "echo Hello - from schedule-4"

workflows:

  # ********** SETUP WORKFLOW **********

  setup-pr:
    when:
      not:
        equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - setup-pr:
          filters:
              branches:
                ignore: master

  setup-master:
    when:
      not:
        equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - setup-master:
          filters:
              branches:
                only: master

  # ********** SCHEDULED WORKFLOW **********

  schedule-1:
    when:
      equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - say-hello-schedule-1

  schedule-2:
    when:
      equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - say-hello-schedule-2

  schedule-3:
    when:
      equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - say-hello-schedule-3

  schedule-4:
    when:
      equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - say-hello-schedule-4

