version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Say hello - PR
          command: "echo Hello - from PR"

workflows:
  say-hello:
    jobs:
      - say-hello
